const trajlonEvents = [
    {
        id: 1,
        related_id: 19,
        imgSrc: "/asset/effectiveimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "23",
        monthYear: "June, 2026",
        location: "Sandton, South Africa",
        startTime: "23",
        endTime: "27 June 2026",
        participants: "150",
        regEndDate: "18/06/2026",
        skillLevel: "Procurement Management",
        title: "Effective Specifications Writing",
        slug: "effective-specifications-writing",
        seo: {
            seoTitle: "Effective Specifications Writing Workshop | Procurement Event | SkillHub International",
            seoDescription: "Join the Effective Specifications Writing event in Sandton, South Africa. Enhance your procurement management skills with expert-led sessions on writing clear and effective specifications. Register now for this essential procurement event!",
            seoKeywords: "specifications writing workshop, procurement event South Africa, operations training, procurement management, Sandton events, SkillHub International events",
            seoHeading: "Effective Specifications Writing: Procurement Management Workshop",
        },
    },
    {
        id: 2,
        related_id: 17,
        imgSrc: "/asset/railwayOperations.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "13",
        monthYear: "July, 2026",
        location: "Cape Town, South Africa",
        startTime: "13",
        endTime: "15 July 2026",
        participants: "150",
        regEndDate: "08/07/2026",
        skillLevel: "Procurement Management",
        title: "Practical Railway Operations and Service Delivery",
        slug: "practical-railway-operations-and-service-delivery",
        seo: {
            seoTitle: "Practical Railway Operations and Service Delivery Seminar | Procurement Event | SkillHub International",
            seoDescription: "Attend the Practical Railway Operations and Service Delivery seminar in Cape Town. Learn best practices and strategies to prevent and detect procurement fraud in your organization. Secure your spot at this vital procurement management event.",
            seoKeywords: "railway operations seminar, service delivery, procurement management event, Cape Town events, SkillHub International events, anti-fraud training",
            seoHeading: "Practical Railway Operations and Service Delivery: Procurement Risk Management",
        },
    },
    {
        id: 3,
        related_id: 30,
        imgSrc: "/asset/supervisoryimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "24",
        monthYear: "August, 2026",
        location: "Sandton, South Africa",
        startTime: "24",
        endTime: "26 August 2026",
        participants: "150",
        regEndDate: "19/08/2026",
        skillLevel: "Procurement Management",
        title: "Strategic Railway Management",
        slug: "strategic-railway-management",
        seo: {
            seoTitle: "Strategic Railway Management Training | SkillHub International",
            seoDescription: "Join our Strategic Railway Management training in Sandton. Enhance your leadership and management capabilities in procurement. Register now for this essential workshop!",
            seoKeywords: "supervisory management training, procurement leadership skills, operations management, Sandton events, SkillHub International training",
            seoHeading: "Advanced Supervisory Management Skills: Leadership Training",
        },
    },
    {
        id: 4,
        related_id: 4,
        imgSrc: "/asset/advancedPorts.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "21",
        monthYear: "September, 2026",
        location: "Durban, South Africa",
        startTime: "21",
        endTime: "25 September 2026",
        participants: "150",
        regEndDate: "16/09/2026",
        skillLevel: "Ports & Shipping Management",
        title: "Advanced Principles in Ports and Marine Terminals Management",
        slug: "advanced-principles-in-ports-and-marine-terminals-management",
        seo: {
            seoTitle: "Advanced Principles in Ports and Marine Terminals Management | SkillHub International",
            seoDescription: "Enhance your expertise in ports and marine terminals management at our advanced training in Durban. Learn best practices and strategies for effective port operations. Register today!",
            seoKeywords: "ports management training, marine terminals management, logistics, Durban events, SkillHub International training",
            seoHeading: "Advanced Principles in Ports and Marine Terminals Management",
        },
    },
    {
        id: 5,
        related_id: 31,
        imgSrc: "/asset/aiAndDataimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "26",
        monthYear: "October, 2026",
        location: "Dubai, AUE",
        startTime: "26",
        endTime: "28 October 2026",
        participants: "150",
        regEndDate: "22/10/2026",
        skillLevel: "Business Management",
        title: "Artificial Intelligence Strategy for Business Professionals",
        slug: "artificial-intelligence-strategy-for-business-professionals",
        seo: {
            seoTitle: "Artificial Intelligence Strategy for Business Professionals | SkillHub International",
            seoDescription: "Join the Artificial Intelligence Strategy for Business Professionals conference in Dubai. Explore the latest trends and innovations in global logistics and operations. Network with industry leaders and enhance your knowledge.",
            seoKeywords: "AI in operations, data analytics conference, global logistics, Dubai events, SkillHub International conference",
            seoHeading: "Artificial Intelligence Strategy for Business Professionals",
        },
    },
    {
        id: 6,
        related_id: 15,
        imgSrc: "/asset/transport.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "17",
        monthYear: "November, 2026",
        location: "Sandton, South Africa",
        startTime: "17",
        endTime: "21 November 2026",
        participants: "150",
        regEndDate: "16/11/2026",
        skillLevel: "Transport and Distribution Management",
        title: "Transport and Fleet Management",
        slug: "transport-and-fleet-management",
        seo: {
            seoTitle: "Transport and Fleet Management Training | SkillHub International",
            seoDescription: "Enhance your transport and fleet management skills at our training in Sandton. Learn effective strategies for managing transportation and logistics operations. Register now!",
            seoKeywords: "transport management training, fleet management skills, logistics, Sandton events, SkillHub International training",
            seoHeading: "Transport and Fleet Management: Logistics Training",
        },
    },
]

export default trajlonEvents;